### ISSUE TITLE
Excessive dependencies for this package

### ISSUE THREAD

**Issue by dzbarsky** [firebase/firebase-admin-go#187]
Hello,

It appears that compiling this project requires pulling in quite a few dependencies. After looking at the code a bit, it appears that things like grpc, opencencus, and some of the cloud APIs should not be necessary for simple usage (I am only using this package to call VerifyIDToken).

Could this package be refactored so that users don't need to compile a ton of packages to get simple functionality?

**Comment by hiranya911** [comment]
Most of those dependencies are coming through Cloud Storage and Firestore, and they are critical for our users. They do not cause any runtime overhead. `go get` overhead is around 45 seconds on Travis (which should get amortized over a long time on developer workstations), and the compilation overhead is 1-2 seconds.

**Comment by dzbarsky** [comment]
Hi, I understand your point, I am not asking you to remove them from the overall repo because I do understand some of your users get value from them. All I am asking is for the package to be refactored such that it is possible to compile a portion of it (say an `auth` subpackage) to do what I want without needing everything else.

The reason I am asking is because our deployment builds are from-scratch (limitation/feature of the platform we are using) so we do see the 45 seconds overhead more often than you would expect.

I might even contribute a PR myself once I get annoyed enough, but in the meantime can you reopen this issue if you agree that such a refactoring would be acceptable?

**Comment by dzbarsky** [comment]
@hiranya911 ^^

**Comment by dzbarsky** [comment]
@hiranya911 friendly ping, would you accept a refactoring as I suggested above?

**Comment by hiranya911** [comment]
@dzbarsky that depends on the exact nature and scope of the refactor. If you outline your proposed changes, and point out how it will impact the public API surface, we will be happy to take a look.

**Comment by dzbarsky** [comment]
A step in the right direction would be to define an option interface in your package rather than using this one: https://github.com/googleapis/google-api-go-client/blob/master/option/option.go#L27

However that wouldn't solve the issue, because https://godoc.org/google.golang.org/api/internal#DialSettings still depends on grpc.

A better design would be to abstract out the transport from the application logics and make it pluggable at a higher layer rather than all the way at the bottom, and to have separate options for the transport mechanism vs the authentication (api key/token).

Unfortnately I don't see a way offhand to do this without changes to the `google.golang.org/api` package.

**Comment by hiranya911** [comment]
That makes it quite complicated. The Google API client for Go is developed by a different team, so they are the people you really need to convince. To provide some historical context:

1. The API client team has been pretty adamant from the start that the Firebase Admin SDK should use the same options and the credentials as the API client. I wasn't a huge fan of this idea at first, but later came to like it since it made using application default credentials, and other GCP libraries like Storage and Firestore extremely easy. Being able to use Firebase and GCP libraries together is a priority for us.
2. We have adopted a similar approach for passing configuration/credentials in other languages too. Java and .NET already do this, and Node.js and Python are also heading that way.
3. The changes you propose seem to be breaking API changes. We are somewhat reluctant to make such changes, but we'll do it when it's necessary, and there's enough consensus among teams.

My recommendation at this point would be to start a discussion over at https://github.com/googleapis/google-api-go-client and get their opinion on the matter. If they can refactor their implementation, then chances are we won't even have to make any significant changes in our code (except for may be refactoring the `Firestore()` and `Storage()` functions out of the `App` type -- but we can figure something out for that).
