### ISSUE TITLE
FR: Adding of interfaces in order to support mocking

### ISSUE THREAD

**Issue by Megalepozy** [firebase/firebase-admin-go#219]
Currently its complicated to unit test the usage (not its implementation) of this pkg cause it lack interfaces for mocking, my current solution is to encapsulate all of the pkg usage in a new pkg and supply interface for that but it will be a lot easier for developers to implement mocking if there were interfaces available.

Or maybe I just miss something? :)

**Comment by hiranya911** [comment]
@Megalepozy Go best practice is to declare interfaces at the consumer's end of an API. That means developers should declare interfaces for the subset of the SDK APIs they actually use. It seems you're already doing it, but I'll describe it a bit further for everyone's benefit.

For example suppose you have the following function that uses the Firebase SDK to set custom claims on a user:

```
func DoSomething(client *auth.Client) {
   // logic
  err := client.SetCustomUserClaims(ctx, uid, claims)
  // more logic
}
```

To make this code more amenable for testing, developers should declare an interface to abstract out the use of the Firebase SDK.

```
type ClaimsSetter interface {
  func SetCustomUserClaims(context.Context, string, map[string]interface{}) error
}

func DoSomething(setter ClaimsSetter) {
   // logic
  err := setter.SetCustomUserClaims(ctx, uid, claims)
  // more logic
}
```

Now the production can code call `DoSomething()` with an `auth.Client` since it implicitly implements the new interface. Testing code can declare a mock claims setter for testing purposes.

For further reading: https://github.com/golang/go/wiki/CodeReviewComments#interfaces

We have very few public interfaces declared in the SDK. Even in those cases, the Golang experts in the Google Cloud team later told us that we probably shouldn't have exposed them.
