### ISSUE TITLE
not function with option.WithHTTPClient

### ISSUE THREAD

**Issue by jarod** [firebase/firebase-admin-go#244]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: CentOS 7
  * Library version: 3.7.0
  * Firebase Product: messaging

#### Steps to reproduce:

run below code. 
firebase.NewApp without clientOpt it work perfectly.
firebase.NewApp with clientOpt return error `invalid character '<' looking for beginning of value`
I add some logging code to firebase admin sdk code. the error happen because the api response a html page. and the library try to unmarshal the the response body as json value.

I need to use a custom http.Client instance because I will need to set proxy on some environment.

#### Relevant Code:

```go
func main() {
        ctx := context.Background()
        clientOpt := option.WithHTTPClient(&http.Client{})
        app, err := firebase.NewApp(ctx, nil, clientOpt)
        if err != nil {
              fmt.Println("Failed to create firebase app:", err)
        }
        mc, err := app.Messaging(ctx)
        if err != nil {
              fmt.Println("Failed to create firebase messaging client: ", err)
        }
        tokens := []string{
                "my valid registrationToken",
        }
        res, err := mc.SubscribeToTopic(ctx, tokens, "topic1")
        fmt.Printf("SubscribeToTopic - res=%v,err=%v\n", res, err)
}
```
OUTPUT:
```bash
SubscribeToTopic - res=<nil>,err=invalid character '<' looking for beginning of value
```

**Comment by hiranya911** [comment]
This is working as intended.

If you're going to specify your own `HTTPClient` then you should also take care of request authorization. Otherwise all RPC calls will fail with an 401 (or perhaps 403) response. That's the html response you're getting.

The usual way to configure a proxy for Google/Firebase Go libraries is by setting the `HTTPS_PROXY` environment variable. See: https://medium.com/faun/firebase-accessing-firestore-and-firebase-through-a-proxy-server-c6c6029cddb1
