### ISSUE TITLE
Why is the client context not used in verifyIDToken?

### ISSUE THREAD

**Issue by Xeoncross** [firebase/firebase-admin-go#268]
For some reason the `ctx` that is passed in is not used, instead a new blank context is created for no purpose.

https://github.com/firebase/firebase-admin-go/blob/79d5dcdeff7f536eb11a549dd25579d88831d19e/snippets/auth.go#L80-L82

**Comment by hiranya911** [comment]
No particular reason. One could argue that since only the code between the `[START]` and `[END]` tags are actually rendered in the website, using `context.Background()` results in a less ambiguous example. But I see `ctx` variable being used almost everywhere in these snippets, so it's probably safer (and better) to do the same here.

**Comment by Xeoncross** [comment]
Using the provided ctx would allow the requester to cancel if needed. `context.Background()` will never cancel and severs the link between the caller.

**Comment by hiranya911** [comment]
You're welcome to provide a PR to update the snippet. But I don't think it's too critical, since we don't render the `verifyToken()` signature in the HTML output: https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_the_firebase_admin_sdk

**Comment by hiranya911** [comment]
@lahirumaramba this is a trivial change. Might be a good place for you to start.
