### ISSUE TITLE
WithCredentialsJSON and WithHTTPClient options doesn't work together

### ISSUE THREAD

**Issue by asidorochev** [firebase/firebase-admin-go#400]
### Environments

  * Operating System version: all
  * Firebase SDK version: v4.0.0
  * Firebase Product: messaging

#### Steps to reproduce:

If I use only WithCredentialsJSON option to create Firebase App, it works with no problem. But if I use both WithCredentialsJSON and WithHTTPClient options, I got error while sending message: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."

#### Working code:

```
opt := []option.ClientOption{
    option.WithCredentialsJSON(credentials),
}

app, _ := firebase.NewApp(ctx, config, opt...)
client, _ := app.Messaging(ctx)
_, err := client.Send(ctx, message)
```

#### Not working code:

```
opt := []option.ClientOption{
    option.WithCredentialsJSON(credentials),
    option.WithHTTPClient(&http.Client{}),
}

app, _ := firebase.NewApp(ctx, config, opt...)
client, _ := app.Messaging(ctx)
_, err := client.Send(ctx, message)
```

**Comment by hiranya911** [comment]
Unfortunately that's by design. The [documentation](https://godoc.org/google.golang.org/api/option#WithHTTPClient) mentions this:

> When used, the WithHTTPClient option takes precedent over all other supplied options.

If you think this behavior should change I'd advise filing an issue at https://github.com/googleapis/google-api-go-client

The only other alternative is to initialize an `oauth2.Transport` instance with the right credentials, and pass that into your `http.Client`. See the examples in https://github.com/firebase/firebase-admin-go/issues/397#issuecomment-676856380
